version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${DB_NAME} -U ${DB_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    container_name: ewallet
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local